### ISSUE TITLE
How to respond with "data" directly?

### ISSUE THREAD

**Issue by caioedut** [Howard86/next-api-handler#67]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

I just don't want props "success"/"error" and data on my response.

**Comment by Howard86** [comment]
following https://github.com/Howard86/next-api-handler/blob/main/src/lib/router-builder.ts#L88-L91
```
  res.status(200).json({
    success: true,
    data,
  });
  ```
  
  atm we cannot update response format from `router-builder`
  
  ideally we should have a response dto that we can customise the response
